export const UPD_CHAIN_ID = 'UPD_CHAIN_ID';
export const UPD_SELECTED_ADDRESS = 'UPD_SELECTED_ADDRESS';
export const UPD_METAMASK_ENABLED = 'UPD_METAMASK_ENABLED';
export const UPD_METAMASK_ERROR = 'UPD_METAMASK_ERROR';
export const UPD_METAMASK_CONFLICTS = 'UPD_METAMASK_CONFLICTS';
