export const icons = {
  home: 'mdi-home-assistant',
  close: 'mdi-close',
  eth: 'mdi-ethereum',
  gas: 'mdi-gas-station-outline',
  diamonds: 'mdi-diamond-stone',
  dashboard: 'mdi-view-dashboard',
  navMenuOpen: 'mdi-menu-open',
  navMenu: 'mdi-menu',
  logout: 'mdi-logout',
  close: 'mdi-close',
  navDecrease: 'mdi-format-indent-decrease',
  navIncrease: 'mdi-format-indent-increase',
  vpn: 'mdi-vpn',
  netKey: 'mdi-folder-key-network-outline',
  cableData: 'mdi-cable-data',
  vpnGlobe: 'mdi-globe-model',
  vpnPac: 'mdi-router-network',
  refresh: 'mdi-refresh',
  networkEnabled: 'mdi-check-network-outline',
  networkDisabled: 'mdi-close-network-outline',
  powerButton: 'mdi-power-standby',
  copy: 'mdi-content-copy',
  rightforward: 'mdi-forwardburger',
  leftback: 'mdi-backburger',
  fullScreen: 'mdi-fullscreen',
  fullScreenExit: 'mdi-fullscreen-exit',
};
